### ISSUE TITLE
update logger settings to avoid disk space issues

### ISSUE THREAD

**Issue by ebenenglish** [boston-library/curator_app#3]
Set logging in staging and production to use rolling logs based on log size.

Make changes to:
* /config/environments/staging.rb
* /config/environments/production.rb

 This pattern should work:
```ruby
# rolling logs, no more than 10 files, 100MB max size each
config.logger = ActiveSupport::Logger.new("#{Rails.root}/log/#{Rails.env}.log", 10, 104_857_600)
```

**Comment by bbarberBPL** [comment]
closed with fbb690bd4a80871aa4de7acff3bf89516d8c023e
